# Generated by Django 3.0.1 on 2019-12-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_remove_list_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='list',
            name='text',
            field=models.TextField(default=' '),
        ),
    ]
